default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres   
  password: umgundi
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: umgundi_development

test:
  <<: *default
  database: umgundi_test

