default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['POSTGRES_USER'] || 'postgres' %>
  password: <%= ENV['POSTGRES_PASSWORD'] || '' %>
  host: <%= ENV['PGHOST'] || 'localhost' %>

development:
  <<: *default
  database: umgundi_development

test:
  <<: *default
  database: umgundi_test
